name: Test
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build cache
        uses: ./.github/actions/cache_cargo
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all -- --nocapture
